[battery]
nominalInternalResistance   = 0.005
capacityAh                  = 2.0
nominalVoltage              = 22.2
cellCount                   = 3.0
currentCapacity             = 100.0
soc                         = 1.0
safteyTerminationLevel      = 0.2