[battery]

nominalInternalResistance   = 
capacityAh                  = 
nominalVoltage              = 
cellCount                   = 
wattHours                   = 
currentCapacity             = 
soc                         = 1
safetyTerminationLevel      = 