[battery]
nominalInternalResistance   = 0.005
capacityAh                  = 2000.0
nominalVoltage              = 12.0
cellCount                   = 8.0
wattHours                   = 100.0
currentCapacity             = 100.0
soc                         = 1.0
safetyTerminationLevel      = 0.2
