[vehicle]
wind = [0.0,0.0,0.0]
gravitationalAcceleration = -9.81
targetLandingPosition  = [400000.0,0.0,0.0]
initPosition=[0.0,0.0,20.0]
initVehicleState = [0.0,0.0,1.0]
MOI = [2,2,2]
initVelocity = [0.0,0.0,0.0]
centerOfPressure = 0.0
maxGAllowedEntry = 4.5
cogToEngine = -8.0
timeStep = 0.001
mass = 1
maxCruiseVelocity = 8.0
[PID]
Kp = 2.4
Ki = 0.6
Kd = 2.2

ZKp = 26.5
ZKi = 1.2
ZKd = 2.4

Kvp = 21.1
Kvi = 2.0
Kvd = 0.9

ZKvp = 29.3
ZKvi = 2.6
ZKvd = 4.2

AKp = 21.0
AKi = 2.9
AKd = 2.7
[accelerometer]
frequency = 1000.0
NoisePowerSpectralDensity = 3.0
bandwidth = 100.0
bias = 0.0
burst = true
burstStdDeviation = 2.0
maxBurstDuration = 0.5
[gps]
frequency = 10.0
NoisePowerSpectralDensity = 0.02
bandwidth = 100.0
bias = 0.0
burst = true
burstStdDeviation = 0.1
maxBurstDuration = 1.0
[gyro]
frequency = 10.0
NoisePowerSpectralDensity = 3.0
bandwidth = 100.0
bias = 0.0
burst = true
burstStdDeviation = 0.5
maxBurstDuration = 0.4