[motor]
name = "T-Motor MN1010"
    freeSpeedRpm   =
    stallTorque    = 
    stallCurrent   = 
    noLoadCurrent  =  
    resistance     = 
    voltage        = 
    kv             =  
    kt             = 