[motor]
name = "T-Motor MN1010"
    freeSpeedRpm   = 5000.0
    stallTorque    = 0.5
    stallCurrent   = 50.0
    noLoadCurrent  =  3.0
    resistance     = 1.5
    voltage        = 30.0
    kv             =  400.0
    kt             = 0.02